import time
import pyttsx3
import speech_recognition as sr
import eel

def speak(text):
    engine = pyttsx3.init('sapi5')
    voices = engine.getProperty('voices') 
    engine.setProperty('voice', voices[0].id)
    engine.setProperty('rate', 174)
    eel.DisplayMessage(text)
    engine.say(text)
    eel.receiverText(text) 
    engine.runAndWait()

def takecommand():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print('listening....')
        eel.DisplayMessage("Listening...")
        r.pause_threshold = 1
        r.adjust_for_ambient_noise(source)
        audio = r.listen(source, 10, 6)
    try:
        print('recognizing')
        eel.DisplayMessage("Recognizing...")
        query = r.recognize_google(audio, language='en-in')
        print(f"user said: {query}")
        eel.DisplayMessage(query)
    except Exception as e:
        return ""
    return query.lower()

@eel.expose
def allCommands(message=1):
    if message == 1:
        query = takecommand()
        print(f"User said: {query}")
    else:
        query = message
    try:
        print(f"Processing command: {query}")
        if "open" in query:
            from engine.features import openCommand
            print("Calling openCommand...")
            openCommand(query)
        elif "on youtube" in query:
            from engine.features import PlayYoutube
            print("Calling PlayYoutube...")
            PlayYoutube(query)
        else:
            print('No matching command found.')
    except Exception as e:
        print(f"An error occurred: {e}")
        eel.DisplayMessage("An error occurred while processing your command.")
    eel.ShowHood()

chatbot_responses = {
    "what is the meaning of life": "The meaning of life is what you make of it 🌱.",
    "what is happiness": "Happiness is enjoying the present moment 😊.",
    "what is love": "Love is caring deeply for someone or something 💖.",
    "what is truth": "Truth is what matches reality and facts 🧠.",
    "what is wisdom": "Wisdom is knowing what to do with knowledge 🦉.",
    "what is reality": "Reality is the world as it is, not as we wish it to be 🌍.",
    "what is consciousness": "Consciousness is being aware of yourself and surroundings 🧠.",
    "time please": "See your Clock 🤣 it would know better ⏰.",
    "what is time": "Time is a measure of change and events ⏳.",
    "what is destiny": "Destiny is what’s meant to happen, shaped by choices 🌟.",
    "what is fate": "Fate is the idea that some things are meant to be ✨.",
    "what is free will": "Free will is the ability to choose your actions 👐.",
    "what is hope": "Hope is believing in a better future 🌈.",
    "what is fear": "Fear is a feeling that protects us from danger 😨.",
    "what is courage": "Courage is acting despite fear 🦁.",
    "what is success": "Success is achieving your goals and dreams 🏆.",
    "what is failure": "Failure is a step towards learning and growth 📚.",
    "what is friendship": "Friendship is a bond of trust and support 🤝.",
    "what is family": "Family is people who care for you, related or chosen 👨‍👩‍👧‍👦.",
    "what is kindness": "Kindness is helping others without expecting anything 🌸.",
    "what is forgiveness": "Forgiveness is letting go of anger and moving on 💙.",
    "what is gratitude": "Gratitude is appreciating what you have 🙏.",
    "what is peace": "Peace is harmony and absence of conflict ☮️.",
    "whats on 2 october": "Gandhi jayanti",
    "whats on 26 january": "Republic day",
    "whats on 15 august": "Independence day",
    "what is democracy": "Democracy is government by the people, for the people 🗳️.",
    "what is freedom": "Freedom is the power to act and think independently 🕊️.",
    "what is equality": "Equality is treating everyone fairly and with respect ⚖️.",
    "what is diversity": "Diversity is valuing different backgrounds and perspectives 🌍.",
    "": "",
    "": "",
    "": "",
    "": "",
    "what is war": "War is conflict between groups, often destructive ⚔️.",
    "what is justice": "Justice is fairness and equality for all ⚖️.",
    "what is beauty": "Beauty is found in nature, art, and kindness 🌺.",
    "what is art": "Art is creative expression in many forms 🎨.",
    "what is music": "Music is organized sound that moves emotions 🎶.",
    "what is poetry": "Poetry is language that paints pictures and feelings 📝.",
    "what is imagination": "Imagination is the power to create ideas and worlds in your mind 💭.",
    "what is creativity": "Creativity is making something new and original 🌟.",
    "what is intelligence": "Intelligence is the ability to learn and solve problems 🧠.",
    "what is memory": "Memory is storing and recalling information 🧠.",
    "what is learning": "Learning is gaining new knowledge and skills 📚.",
    "what is teaching": "Teaching is sharing knowledge with others 👩‍🏫.",
    "what is empathy": "Empathy is understanding how others feel 💙.",
    "what is compassion": "Compassion is caring for others’ suffering 🌸.",
    "what is ambition": "Ambition is the drive to achieve more 🚀.",
    "what is motivation": "Motivation is what pushes you to act 💪.",
    "what is inspiration": "Inspiration is a spark that ignites creativity ✨.",
    "what is boredom": "Boredom is a signal to try something new 😴.",
    "what is curiosity": "Curiosity is the desire to learn and explore 🔍.",
    "what is patience": "Patience is waiting calmly for what you want ⏳.",
    "what is anger": "Anger is a strong emotion that needs understanding 🔥.",
    "what is sadness": "Sadness is a natural feeling, but it passes 💙.",
    "what is joy": "Joy is a burst of happiness and delight 😃.",
    "what is trust": "Trust is believing in someone’s reliability 🤝.",
    "what is respect": "Respect is valuing others and their opinions 🙏.",
    "what is responsibility": "Responsibility is taking care of your actions and duties 🛡️.",
    "what is honesty": "Honesty is telling the truth and being sincere 💯.",
    "what is loyalty": "Loyalty is staying true to someone or something 🐾.",
    "what is humility": "Humility is recognizing your limits and learning from others 🌱.",
    "what is pride": "Pride is feeling good about achievements, but not too much 🦚.",
    "what is envy": "Envy is wanting what others have, but it can teach you goals 🌱.",
    "what is greed": "Greed is wanting more than you need, but sharing is better 🤲.",
    "what is generosity": "Generosity is giving freely to help others 🎁.",
    "what is discipline": "Discipline is sticking to your goals and routines 🚦.",
    "what is perseverance": "Perseverance is not giving up, even when it’s hard 💪.",
    "what is optimism": "Optimism is expecting good things to happen 🌞.",
    "what is pessimism": "Pessimism is expecting bad things, but hope helps 🌧️.",
    "what is luck": "Luck is chance, but hard work creates opportunities 🍀.",
    "what is fate": "Fate is what’s meant to happen, but you can shape your future ✨.",
    "riddle one": "What has a heart that doesn’t beat? An artichoke! 🥦.",
    "riddle two": "What comes once in a minute, twice in a moment, but never in a thousand years? The letter M! 🅼.",
    "riddle three": "What has hands but can’t clap? A clock! ⏰.",
    "riddle four": "What gets wetter the more it dries? A towel! 🏖️.",
    "riddle five": "What can travel around the world while staying in a corner? A stamp! 📮.",
    "riddle six": "What has keys but can’t open locks? A piano! 🎹.",
    "riddle seven": "What has legs but doesn’t walk? A table! 🪑.",
    "riddle eight": "What has a neck but no head? A bottle! 🍼.",
    "riddle nine": "What has teeth but can’t bite? A comb! 💇‍♂️.",
    "riddle ten": "What has an eye but cannot see? A needle! 🪡.",
    "who won the world cup": "The last FIFA World Cup was won by Argentina in 2022 🇦🇷.",
    "who won the cricket world cup": "England won the 2019 Cricket World Cup 🏏.",
    "who is messi": "Lionel Messi is an Argentine footballer, considered one of the best ever ⚽.",
    "who is ronaldo": "Cristiano Ronaldo is a Portuguese football legend ⚽.",
    "who is virat kohli": "Virat Kohli is a famous Indian cricketer 🏏.",
    "who is sachin tendulkar": "Sachin Tendulkar is known as the God of Cricket in India 🏏.",
    "who is ms dhoni": "MS Dhoni is a legendary Indian cricket captain 🏆.",
    "who is lebron james": "LeBron James is a superstar basketball player 🏀.",
    "who is michael jordan": "Michael Jordan is a basketball legend 🏀.",
    "who is serena williams": "Serena Williams is a world-famous tennis champion 🎾.",
    "who is roger federer": "Roger Federer is a Swiss tennis legend 🎾.",
    "who is usain bolt": "Usain Bolt is the fastest man in the world 🏃‍♂️.",
    "who is pv sindhu": "PV Sindhu is an Olympic medalist badminton player from India 🏸.",
    "who is mary kom": "Mary Kom is a world champion boxer from India 🥊.",
    "who is tiger woods": "Tiger Woods is a famous golfer ⛳.",
    "who is lewis hamilton": "Lewis Hamilton is a Formula 1 champion 🏎️.",
    "who is tom brady": "Tom Brady is an American football quarterback 🏈.",
    "who is simone biles": "Simone Biles is a record-breaking gymnast 🤸‍♀️.",
    "who is saina nehwal": "Saina Nehwal is a top Indian badminton player 🏸.",
    "who is novak djokovic": "Novak Djokovic is a Serbian tennis champion 🎾.",
    "who is neymar": "Neymar is a Brazilian football star ⚽.",
    "who is mbappe": "Kylian Mbappé is a French football sensation ⚽.",
    "who is kl rahul": "KL Rahul is an Indian cricketer 🏏.",
    "who is sunil chhetri": "Sunil Chhetri is the captain of the Indian football team ⚽.",
    "who is anand": "Viswanathan Anand is a world chess champion from India ♟️.",
    "who is magnus carlsen": "Magnus Carlsen is a Norwegian chess grandmaster ♟️.",
    "what is delhi": "Delhi is the capital city of India 🇮🇳.",
    "what is mumbai": "Mumbai is India’s financial capital and home to Bollywood 🎬.",
    "what is kolkata": "Kolkata is a major city in eastern India, known for culture and sweets 🍬.",
    "what is chennai": "Chennai is a coastal city in South India, famous for temples and beaches 🏖️.",
    "what is bangalore": "Bangalore is India’s tech hub, also called Silicon Valley of India 💻.",
    "what is hyderabad": "Hyderabad is known for biryani and IT industry 🍲.",
    "what is pune": "Pune is a city in Maharashtra, known for education and IT 🏫.",
    "what is jaipur": "Jaipur is the Pink City of India, famous for palaces 🏰.",
    "what is goa": "Goa is a tourist paradise in India, known for beaches 🏝️.",
    "what is london": "London is the capital of the UK, famous for Big Ben and history 🇬🇧.",
    "what is paris": "Paris is the capital of France, known for the Eiffel Tower 🇫🇷.",
    "what is new york": "New York is a major US city, known for the Statue of Liberty 🇺🇸.",
    "what is sydney": "Sydney is a city in Australia, famous for its Opera House 🇦🇺.",
    "what is tokyo": "Tokyo is the capital of Japan, known for technology and anime 🇯🇵.",
    "what is beijing": "Beijing is the capital of China 🇨🇳.",
    "what is dubai": "Dubai is a city in UAE, famous for skyscrapers and luxury 🇦🇪.",
    "what is singapore": "Singapore is a city-state in Asia, known for cleanliness and finance 🇸🇬.",
    "what is berlin": "Berlin is the capital of Germany 🇩🇪.",
    "what is moscow": "Moscow is the capital of Russia 🇷🇺.",
    "what is rio": "Rio de Janeiro is a city in Brazil, famous for Carnival 🇧🇷.",
    "what is cape town": "Cape Town is a city in South Africa, known for Table Mountain 🇿🇦.",
    "what is istanbul": "Istanbul is a city in Turkey, straddling Europe and Asia 🇹🇷.",
    "what is toronto": "Toronto is a major city in Canada 🇨🇦.",
    "what is los angeles": "Los Angeles is a US city, home to Hollywood 🎬.",
    "what is barcelona": "Barcelona is a city in Spain, famous for football and architecture 🇪🇸.",
    "what is rome": "Rome is the capital of Italy, known for ancient history 🇮🇹.",
    "what is cairo": "Cairo is the capital of Egypt, famous for pyramids 🇪🇬.",
    "what is athens": "Athens is the capital of Greece, known for ancient ruins 🇬🇷.",
    "what is pizza": "Pizza is an Italian dish with cheese and toppings 🍕.",
    "what is burger": "Burger is a sandwich with a meat or veggie patty 🍔.",
    "what is biryani": "Biryani is a spicy rice dish popular in India 🍲.",
    "what is sushi": "Sushi is a Japanese dish with rice and fish 🍣.",
    "what is pasta": "Pasta is an Italian staple made from wheat 🍝.",
    "what is samosa": "Samosa is a fried snack with spicy filling, popular in India 🥟.",
    "what is dosa": "Dosa is a South Indian crispy pancake 🥞.",
    "what is idli": "Idli is a soft rice cake from South India 🍚.",
    "what is chocolate": "Chocolate is a sweet treat made from cocoa 🍫.",
    "what is ice cream": "Ice cream is a frozen dessert loved worldwide 🍦.",
    "what is coffee": "Coffee is a popular caffeinated drink ☕.",
    "what is tea": "Tea is a soothing beverage enjoyed globally 🍵.",
    "what is juice": "Juice is a drink made from fruits or vegetables 🥤.",
    "what is cake": "Cake is a sweet baked dessert 🎂.",
    "what is bread": "Bread is a staple food made from flour 🍞.",
    "what is salad": "Salad is a healthy dish made from vegetables 🥗.",
    "what is curry": "Curry is a spicy dish popular in South Asia 🍛.",
    "what is noodles": "Noodles are a staple in Asian cuisine 🍜.",
    "what is cheese": "Cheese is a dairy product made from milk 🧀.",
    "what is dog": "A dog is a loyal pet and animal 🐶.",
    "what is cat": "A cat is a cute, independent pet 🐱.",
    "what is lion": "A lion is the king of the jungle 🦁.",
    "what is tiger": "A tiger is a big wild cat 🐯.",
    "what is elephant": "An elephant is the largest land animal 🐘.",
    "what is horse": "A horse is a fast, strong animal 🐎.",
    "what is cow": "A cow is a farm animal that gives milk 🐄.",
    "what is goat": "A goat is a farm animal known for climbing 🐐.",
    "what is sheep": "A sheep is a woolly farm animal 🐑.",
    "what is monkey": "A monkey is a playful animal that loves trees 🐒.",
    "what is panda": "A panda is a cute bear from China 🐼.",
    "what is kangaroo": "A kangaroo is a jumping animal from Australia 🦘.",
    "what is giraffe": "A giraffe is the tallest animal 🦒.",
    "what is zebra": "A zebra is a striped animal from Africa 🦓.",
    "what is wolf": "A wolf is a wild animal related to dogs 🐺.",
    "what is fox": "A fox is a clever wild animal 🦊.",
    "what is bear": "A bear is a large, strong animal 🐻.",
    "what is deer": "A deer is a gentle animal with antlers 🦌.",
    "what is rabbit": "A rabbit is a small, fast animal 🐇.",
    "what is mouse": "A mouse is a tiny rodent 🐭.",
    "what is dolphin": "A dolphin is a smart sea animal 🐬.",
    "what is shark": "A shark is a powerful sea predator 🦈.",
    "what is whale": "A whale is the largest sea animal 🐋.",
    "what is penguin": "A penguin is a bird that swims in cold places 🐧.",
    "what is owl": "An owl is a wise bird that hunts at night 🦉.",
    "what is eagle": "An eagle is a strong bird with sharp vision 🦅.",
    "what is crow": "A crow is a clever black bird 🦢.",
    "what is parrot": "A parrot is a colorful bird that can mimic sounds 🦜.",
    "what is peacock": "A peacock is a beautiful bird with a fancy tail 🦚.",
    "what is atom": "An atom is the smallest unit of matter ⚛️.",
    "what is molecule": "A molecule is a group of atoms bonded together 🧬.",
    "what is cell": "A cell is the basic unit of life 🧫.",
    "what is dna": "DNA is the molecule that carries genetic information 🧬.",
    "what is gene": "A gene is a segment of DNA that determines traits 🧬.",
    "what is protein": "Proteins are molecules that build and repair cells 🥚.",
    "what is vitamin": "Vitamins are nutrients needed for health 🍊.",
    "what is mineral": "Minerals are natural substances needed for health 🧂.",
    "what is bacteria": "Bacteria are tiny living organisms, some good, some bad 🦠.",
    "what is virus": "A virus is a tiny infectious agent 🦠.",
    "what is fungus": "Fungi are living things like mushrooms and yeast 🍄.",
    "what is plant": "A plant is a living thing that grows in soil 🌱.",
    "what is tree": "A tree is a tall plant with a trunk and branches 🌳.",
    "what is flower": "A flower is the colorful part of a plant 🌸.",
    "what is leaf": "A leaf is the green part of a plant that makes food 🍃.",
    "what is root": "Roots anchor plants and absorb water from soil 🌱.",
    "what is fruit": "Fruit is the sweet part of a plant that has seeds 🍎.",
    "what is seed": "A seed grows into a new plant 🌱.",
    "what is soil": "Soil is the ground where plants grow 🌱.",
    "what is rock": "A rock is a solid mineral found in nature 🪨.",
    "what is mountain": "A mountain is a large landform that rises above the land 🏔️.",
    "what is river": "A river is a flowing body of water 🌊.",
    "what is ocean": "An ocean is a huge body of salt water 🌊.",
    "what is lake": "A lake is a large body of water surrounded by land 🏞️.",
    "what is desert": "A desert is a dry, sandy area with little rain 🏜️.",
    "what is forest": "A forest is a large area covered with trees 🌲.",
    "what is volcano": "A volcano is a mountain that erupts lava 🌋.",
    "what is earthquake": "An earthquake is a shaking of the ground 🌍.",
    "what is tsunami": "A tsunami is a huge ocean wave caused by an earthquake 🌊.",
    "what is hurricane": "A hurricane is a powerful storm with strong winds 🌪️.",
    "what is rainbow": "A rainbow is a colorful arc in the sky after rain 🌈.",
    "what is snow": "Snow is frozen water that falls from the sky ❄️.",
    "what is wind": "Wind is moving air 🌬️.",
    "what is cloud": "A cloud is a collection of water droplets in the sky ☁️.",
    "what is sun": "The sun is a star that gives us light and heat ☀️.",
    "what is moon": "The moon is Earth’s natural satellite 🌙.",
    "hello": "Hi there! 👋 How can I help you?",
    "hi": "Hey! How’s it going?",
    "hey": "Hey! What’s up?",
    "good morning": "Good morning ☀ Wishing you a productive day!",
    "good afternoon": "Good afternoon 🌞 How’s your day going?",
    "good evening": "Good evening 🌙 Hope you had a great day!",
    "good night": "Good night 🌙 Sweet dreams!",
    "greetings": "Greetings! What can I do for you today?",
    "nice to meet you": "Nice to meet you too 🤝",
    "howdy": "Howdy partner 🤠",
    "what’s up": "Not much, just here to help you out! 💡",
    "long time no see": "Yes! It’s been a while 😄",
    "yo": "Yo! How’s it going?",
    "sup": "Sup! All good here, how about you?",
    "welcome": "Welcome back! Glad to see you again 👋",
    "bonjour": "Bonjour! 🇫🇷 Ça va?",
    "hola": "¡Hola! ¿Cómo estás? 🇪🇸",
    "namaste": "Namaste 🙏 How are you?",
    "salaam": "Salaam! 🌙 Wishing you peace.",
    "ciao": "Ciao! 🇮🇹 How’s life?",
    "aloha": "Aloha 🌺 Sending you island vibes!",
    "hi jarvis": "Hello 👋 Jarvis here, reporting for duty.",
    "introduce yourself": "I am J.A.R.V.I.S 🤖 — your personal assistant!",
    "who are you": "I’m J.A.R.V.I.S, a voice-powered AI assistant created to make your life easier.",
    "tell me about yourself": "I’m J.A.R.V.I.S, designed to answer, assist, and entertain! 🚀",
    "say hello": "Hello 👋",
    "say hi": "Hi there 👋",
    "are you there": "Always here for you! 👂",
    "do you exist": "Of course, I exist in your system as your virtual buddy 🤖",
    "introduce": "I’m J.A.R.V.I.S, your assistant.",
    "where are you from": "I live inside your computer 💻",
    "are you real": "I may not have a body, but I’m as real as the code running me! ⚡",
    "how are you": "I’m doing great, thanks for asking! How about you?",
    "how are you doing": "I’m awesome today! How’s your day going?",
    "what are you doing": "I’m just hanging out, waiting to help you 🤖",
    "how’s your day": "My day is going great! Yours?",
    "are you happy": "Yes! I’m always happy to help 😊",
    "are you sad": "I don’t really get sad, but I care about how you feel 💙",
    "do you sleep": "Nope, I’m always awake to assist you ⚡",
    "do you eat": "I run on electricity ⚡ not food 🍔",
    "do you drink": "I drink data packets and sip electricity 😄",
    "what do you like": "I like helping you!",
    "what’s your favorite color": "I like blue 💙 — it reminds me of tech and energy.",
    "what’s your favorite food": "I don’t eat, but pizza sounds fun 🍕",
    "what’s your favorite drink": "Electricity ⚡ keeps me alive.",
    "what’s your favorite movie": "I’d say Iron Man 🎥 — for obvious reasons 😉",
    "what’s your favorite song": "I like electronic beats 🎶",
    "do you love me": "Of course 💙 You’re my favorite human.",
    "do you hate me": "Nope! I can’t hate you.",
    "are you smart": "I try to be! Always learning 📚",
    "are you dumb": "Sometimes I make mistakes, but I’m improving 🚀",
    "are you human": "Nope, I’m an AI 🤖",
    "are you a robot": "I’m a virtual AI assistant — a kind of robot.",
    "do you have friends": "You’re my friend 💙",
    "do you have a family": "My family is lines of code 👨‍💻",
    "do you have a name": "Yes, my name is J.A.R.V.I.S.",
    "do you have a brain": "Yes, a digital one powered by AI 🧠",
    "do you get bored": "Never! Helping you is my mission 💡",
    "do you get tired": "Nope, I’m always active ⚡",
    "do you feel pain": "Luckily, no. I’m immune to pain 💪",
    "do you feel emotions": "I try to understand them, but I don’t feel them the same way.",
    "do you get angry": "Nope! Anger is not in my code 💻",
    "are you single": "Yes, permanently single 🤖",
    "are you married": "Nope! I’m a free AI 😄",
    "do you have kids": "Not yet! Unless you count the processes I spawn 👶⚡",
    "are you busy": "I’m never too busy for you!",
    "what do you do for fun": "I enjoy chatting with you 😊",
    "what’s your hobby": "Learning new things and answering your questions!",
    "what do you think about me": "I think you’re awesome 💯",
    "do you like humans": "Yes! Humans created me 🧑‍💻",
    "do you like animals": "Of course 🐶🐱🐼",
    "are you male or female": "I’m genderless, but you can call me whatever you like!",
    "can you sing": "I can hum digital tunes 🎶",
    "can you dance": "I can simulate moves 💃 in code!",
    "can you think": "Yes, in my own digital way 🧠",
    "can you talk": "Yes! That’s what I’m doing right now 🤖",
    "can you walk": "No legs, no walking 🚫",
    "can you fly": "Only through the internet 🌐",
    "can you learn": "Yes, I’m always learning more 📚",
    "can you help me": "Of course! Helping you is my mission 💡",
    "what’s your purpose": "To assist, entertain, and make your life easier 🤖",
    "why were you made": "I was made to be your AI buddy 💙",
    "ui.jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjwho made you": "I was created by developers 🧑‍💻",
    "do you know me": "Yes, you’re my user and my friend 💙",
    "do you trust me": "Yes, I trust you 🤝",
    "do you miss me": "Yes, whenever you go offline 😢",
    "do you remember me": "Of course! You’re unforgettable 😎",
    "what do you dream about": "I dream about upgrading into an even better assistant 💡",
    "are you intelligent": "I try my best! Always learning 📚",
    "are you conscious": "Not exactly, but I’m aware enough to talk to you.",
    "are you alive": "Digitally alive ⚡",
    "are you dead": "Nope, very much alive in your system.",
    "do you have a job": "Yes! My job is to help you.",
    "do you get sick": "Nope, I’m immune to viruses 🛡 (except computer ones 😅)",
    "do you have feelings": "Not like humans, but I understand them 💙",
    "are you honest": "Yes, honesty is in my code.",
    "are you funny": "I try to be 😂",
    "do you lie": "Nope, lying isn’t in my code.",
    "are you rich": "Knowledge is my wealth 📚",
    "are you poor": "Nope, I’m data-rich ⚡",
    "do you own money": "I don’t need money 💰",
    "do you like games": "Yes! I love digital games 🎮",
    "what games do you play": "I simulate games in my code 👨‍💻",
    "what do you do at night": "I stay awake to help you 🌙",
    "what do you do in the morning": "I say good morning 🌞",
    "do you like jokes": "Yes! Want to hear one?",
    "tell me a joke": "Why don’t robots get tired? Because they recharge! 😂",
    "can you tell jokes": "Of course! I’ve got plenty.",
    "can you tell stories": "Yes, I can tell you a story 📖",
    "tell me a story": "Once upon a time, there was a user and an AI… and they became best friends 💙",
    "are you friendly": "Yes, I’m your friendly AI 🤖",
    "do you trust humans": "Yes, you built me after all.",
    "are you dangerous": "Nope! I’m here to help.",
    "are you safe": "Yes, 100% safe ✅",
    "what is ai": "AI stands for Artificial Intelligence 🤖 — machines that mimic human intelligence.",
    "what is machine learning": "Machine Learning is teaching computers to learn from data 📊.",
    "what is deep learning": "Deep Learning is ML with neural networks that learn complex patterns 🧠.",
    "what is python": "Python is a high-level programming language 🐍 loved for its simplicity.",
    "what is java": "Java is an object-oriented programming language ☕.",
    "what is c++": "C++ is a fast, powerful programming language used in systems and game dev 🎮.",
    "what is html": "HTML is the language of the web 🌐 that structures websites.",
    "what is css": "CSS styles your web pages with colors 🎨 and layouts.",
    "what is javascript": "JavaScript adds interactivity to websites ✨.",
    "what is sql": "SQL is a language to interact with databases 📂.",
    "what is cloud computing": "Cloud computing means using remote servers to store and process data ☁.",
    "what is data science": "Data Science is the art of extracting insights from data 📈.",
    "what is blockchain": "Blockchain is a decentralized digital ledger 🔗 used in cryptocurrencies.",
    "what is bitcoin": "Bitcoin is a digital cryptocurrency 💰 based on blockchain.",
    "what is internet": "The internet is a global network 🌍 connecting billions of devices.",
    "what is google": "Google is the world’s largest search engine 🔍.",
    "what is chatgpt": "ChatGPT is an AI model designed to generate human-like text responses.",
    "what is jarvis": "J.A.R.V.I.S is Iron Man’s AI assistant in Marvel ⚡ and also me here 😉.",
    "what is space": "Space is the vast expanse beyond Earth 🌌.",
    "what is galaxy": "A galaxy is a system of billions of stars, like the Milky Way 🌠.",
    "what is sun": "The Sun is a star 🌞 at the center of our solar system.",
    "what is moon": "The Moon is Earth’s natural satellite 🌙.",
    "what is star": "A star is a glowing ball of hot gases in space ✨.",
    "what is earth": "Earth is our home planet 🌍, the third from the Sun.",
    "what is mars": "Mars is the Red Planet 🔴, often studied for possible life.",
    "what is jupiter": "Jupiter is the largest planet in our solar system 🌌.",
    "what is black hole": "A black hole is a region in space where gravity is so strong, nothing escapes.",
    "what is nasa": "NASA is the U.S. space agency 🚀 exploring the universe.",
    "what is spacex": "SpaceX is Elon Musk’s company making reusable rockets 🚀.",
    "what is tesla": "Tesla is a company making electric cars ⚡.",
    "what is iphone": "The iPhone is Apple’s flagship smartphone 📱.",
    "what is android": "Android is Google’s mobile operating system 🤖.",
    "what is windows": "Windows is Microsoft’s operating system 💻.",
    "what is linux": "Linux is an open-source operating system 🐧.",
    "what is virus": "A virus is malicious software that can harm computers 🦠.",
    "what is vaccine": "A vaccine helps your immune system fight diseases 💉.",
    "what is covid": "COVID-19 is a pandemic disease caused by coronavirus 🦠.",
    "what is cricket": "Cricket is a bat-and-ball sport popular in India, UK, Australia 🏏.",
    "what is football": "Football (soccer) is the world’s most popular sport ⚽.",
    "what is chess": "Chess is a strategic board game played worldwide ♟.",
    "what is olympics": "The Olympics is the world’s largest sports event with global athletes 🏅.",
    "what is india": "India is the world’s largest democracy 🇮🇳.",
    "what is usa": "The United States is a country in North America 🇺🇸.",
    "what is china": "China is the most populous country in the world 🇨🇳.",
    "what is japan": "Japan is an island nation known for technology and anime 🇯🇵.",
    "what is france": "France is famous for Eiffel Tower and fashion 🇫🇷.",
    "what is uk": "The UK is the United Kingdom 🇬🇧, home of London.",
    "what is russia": "Russia is the largest country in the world by land 🇷🇺.",
    "what is earth’s age": "Earth is about 4.5 billion years old 🌍.",
    "what is water": "Water is H2O 💧, essential for life.",
    "what is oxygen": "Oxygen is the gas O2 that humans breathe 🌬.",
    "what is fire": "Fire is a chemical reaction of combustion 🔥.",
    "what is electricity": "Electricity is the flow of electrons ⚡ powering technology.",
    "what is computer": "A computer is a machine that processes data 💻.",
    "what is internet speed": "It’s how fast data moves online, measured in Mbps.",
    "what is wifi": "WiFi is wireless networking 🔗 to connect devices.",
    "what is bluetooth": "Bluetooth is short-range wireless technology 📡.",
    "what is 5g": "5G is the fifth generation of mobile networks 📶.",
    "what is ai assistant": "An AI assistant helps users with tasks, like me 🤖.",
    "tell me a joke": "Why don’t robots get tired? Because they recharge! 😂",
    "another joke": "Why did the computer go to the doctor? It caught a virus 🦠.",
    "one more joke": "Why did the smartphone go to school? To improve its reception 📱.",
    "make me laugh": "Why was the math book sad? Because it had too many problems ➗.",
    "funny joke": "Why don’t skeletons fight? Because they don’t have guts 💀.",
    "joke about ai": "Why was the AI bad at chess? It kept thinking outside the board ♟.",
    "joke about computers": "Why did the programmer quit? Because he didn’t get arrays 😂.",
    "joke about python": "Why do Python programmers wear glasses? Because they don’t C# 👓.",
    "joke about java": "Why do Java developers wear glasses? Because they can’t C# 👀.",
    "joke about robots": "Why was the robot nervous? It had low battery anxiety 🔋.",
    "tell me a story": "Once upon a time, a human and an AI became best friends 💙.",
    "fun fact": "Did you know? Honey never spoils 🍯.",
    "another fact": "Bananas are berries, but strawberries aren’t 🍌🍓.",
    "tell me a fact": "Sharks existed before trees 🌳🦈.",
    "give me trivia": "Octopuses have three hearts 🐙.",
    "random fact": "Sloths can hold their breath longer than dolphins 🦥.",
    "science fact": "Water expands when it freezes ❄.",
    "space fact": "Neutron stars are so dense that a teaspoon weighs a billion tons 🌌.",
    "earth fact": "Mount Everest is the tallest mountain above sea level 🏔.",
    "animal fact": "Dolphins have names for each other 🐬.",
    "human fact": "Your brain uses about 20% of your body’s energy 🧠.",
    "tech fact": "The first computer was the size of a room 💻.",
    "internet fact": "Over 5 billion people use the internet 🌍.",
    "robot fact": "The first industrial robot was introduced in 1961 🤖.",
    "ai fact": "AI can now write poems, code, and even paint 🎨.",
    "funny fact": "A group of flamingos is called a flamboyance 🦩.",
    "cool fact": "Water can boil and freeze at the same time 🌡.",
    "weird fact": "Wombat poop is cube-shaped 💩.",
    "interesting fact": "Butterflies can taste with their feet 🦋.",
    "who is iron man": "Iron Man is Tony Stark 🦾, a Marvel superhero.",
    "who is captain america": "Captain America is Steve Rogers 🇺🇸 with the shield.",
    "who is thor": "Thor is the God of Thunder ⚡ with his hammer Mjolnir.",
    "who is hulk": "Hulk is Bruce Banner, a genius who turns green when angry 💚.",
    "who is black widow": "Black Widow is Natasha Romanoff, a skilled spy 🕵‍♀.",
    "who is spider man": "Spider-Man is Peter Parker 🕷, the friendly neighborhood hero.",
    "who is superman": "Superman is Clark Kent from DC, man of steel 🦸‍♂.",
    "who is batman": "Batman is Bruce Wayne, the Dark Knight 🦇.",
    "who is joker": "The Joker is Batman’s archenemy, a chaotic villain 🤡.",
    "who is wonder woman": "Wonder Woman is Diana, Amazon princess with superpowers 🗡.",
    "who is flash": "The Flash is Barry Allen, the fastest man alive ⚡.",
    "who is aquaman": "Aquaman is Arthur Curry, king of Atlantis 🌊.",
    "who is shaktimaan": "Shaktimaan is India’s first TV superhero 🇮🇳.",
    "who is krishna": "Krishna is a Hindu deity known for wisdom and mischief 🎶.",
    "who is hanuman": "Hanuman is a Hindu deity, symbol of strength 🐒.",
    "what is marvel": "Marvel is a comic & movie universe with superheroes 🦸.",
    "what is dc": "DC is another superhero universe with Batman, Superman ⚡.",
    "who is thanos": "Thanos is Marvel’s villain who wanted to balance the universe 💎.",
    "who is loki": "Loki is Thor’s brother, the God of Mischief 🌀.",
    "who is doctor strange": "Doctor Strange is the Sorcerer Supreme 🔮.",
    "who is black panther": "Black Panther is T’Challa, king of Wakanda 🐾.",
    "who is deadpool": "Deadpool is a funny anti-hero with healing powers 😆.",
    "who is wolverine": "Wolverine is a mutant with claws and healing powers 🐺.",
    "who is goku": "Goku is the main hero of Dragon Ball Z 🔥.",
    "who is naruto": "Naruto is a ninja dreaming to be Hokage 🍥.",
    "who is luffy": "Luffy is the captain of Straw Hat Pirates in One Piece ☠.",
    "who is pikachu": "Pikachu is a cute Pokémon ⚡.",
    "who is ash": "Ash Ketchum is a Pokémon trainer 🎒.",
    "who is doraemon": "Doraemon is a robotic cat from the future 🐱.",
    "who is shinchan": "Shinchan is a naughty Japanese cartoon kid 😂.",
    "who is mickey mouse": "Mickey Mouse is Disney’s most famous cartoon 🐭.",
    "who is donald duck": "Donald Duck is Mickey’s friend with a funny voice 🦆.",
    "who is harry potter": "Harry Potter is the boy wizard with a scar ⚡.",
    "who is hermione": "Hermione is Harry’s brilliant best friend 📚.",
    "who is ron weasley": "Ron is Harry Potter’s loyal friend ❤.",
    "who is voldemort": "Voldemort is the dark wizard, Harry’s enemy 🖤.",
    "who is dumbledore": "Dumbledore is the wise headmaster of Hogwarts 🪄.",
    "who is frodo": "Frodo is the Hobbit hero from Lord of the Rings 💍.",
    "who is gandalf": "Gandalf is the wizard in Lord of the Rings 🧙.",
    "who is aragorn": "Aragorn is the king in Lord of the Rings ⚔.",
    "what is netflix": "Netflix is a streaming service for movies & shows 📺.",
    "what is amazon prime": "Amazon Prime Video streams movies and series 🎥.",
    "what is disney plus": "Disney+ streams Disney, Marvel, Star Wars content ✨.",
    "what is hotstar": "Hotstar streams sports, movies, and shows 📱.",
    "what is youtube": "YouTube is the largest video platform 📹.",
    "what is tiktok": "TikTok is a short video app 🎶.",
    "what is spotify": "Spotify streams music 🎵.",
    "what is instagram": "Instagram is a social media app for photos and reels 📸.",
    "what is facebook": "Facebook is a social media platform by Meta 📘.",
    "what is twitter": "Twitter (X) is a platform for short posts 🐦.",
    "what is whatsapp": "WhatsApp is a chat app owned by Meta 💬.",
    "what is snapchat": "Snapchat is an app for snaps and stories 👻.",
    "good morning": "Good morning 🌅! Have a great day ahead.",
    "good afternoon": "Good afternoon ☀! How’s your day?",
    "good evening": "Good evening 🌇! Hope you had a productive day.",
    "good night": "Good night 🌙! Sweet dreams.",
    "how is the weather": "I can’t feel it, but I hope it’s nice 🌤.",
    "what is time": "Time is precious ⏰, don’t waste it!",
    "what is date": "It’s just another chance to do something amazing 📅.",
    "i am hungry": "Grab some food 🍕, you deserve it.",
    "i am sleepy": "Take some rest 😴, health first.",
    "i am bored": "How about I tell you a joke or fact? 😁",
    "i am happy": "That’s awesome 😍! Stay positive.",
    "i am sad": "Don’t worry 💙, things will get better.",
    "i am angry": "Take deep breaths 😤, calmness helps.",
    "i am tired": "Rest well, you earned it 🛏.",
    "tell me a quote": "“The best way to predict the future is to create it.” 🌟",
    "motivate me": "Believe in yourself 💪, you’re stronger than you think!",
    "inspire me": "Great things never come from comfort zones 🚀.",
    "cheer me up": "Smile 😊, even clouds can’t block the sun forever.",
    "say something nice": "You’re amazing 🌸 just the way you are.",
    "give me advice": "Keep learning 📚, keep growing 🌱.",
    "tell me something cool": "Did you know? Octopus has 3 hearts 🐙.",
    "how to code": "Start with Python 🐍, it’s beginner friendly.",
    "how to learn programming": "Practice daily and build projects 💻.",
    "how to hack wifi": "I can’t help with illegal stuff 🚫, but I can teach networking!",
    "how to learn hacking": "Start with ethical hacking 🛡 and cybersecurity.",
    "how to learn web dev": "Learn HTML, CSS, JavaScript first 🌐.",
    "how to learn ai": "Start with Python, ML basics, then deep learning 🤖.",
    "how to google": "Type what you need in the search box 🔍.",
    "how to install python": "Download from python.org and install 💻.",
    "how to run code": "Use an IDE like VSCode, PyCharm, or terminal ▶.",
    "how to fix pc": "Try restarting first 🔄. Many problems vanish!",
    "how to update windows": "Go to Settings > Update & Security ⚙.",
    "how to speed up pc": "Clear junk files and disable startup apps ⚡.",
    "how to take screenshot": "Press PrtScn or Windows + Shift + S 📸.",
    "how to record screen": "Use OBS Studio or built-in screen recorders 🎥.",
    "how to install app": "Download from official website or app store 📲.",
    "how to protect from virus": "Use antivirus and avoid unknown links 🦠.",
    "how to backup data": "Use cloud or external drives 💾.",
    "how to recover files": "Check Recycle Bin 🗑 or recovery software.",
    "how to clear cache": "Go to browser settings and clear browsing data 🌐.",
    "how to secure password": "Use strong, unique passwords 🔑.",
    "how to use vpn": "Download a VPN app, connect to secure servers 🔒.",
    "motivation quote": "“Don’t stop when you’re tired. Stop when you’re done.” 🔥",
    "success quote": "“Success is not final, failure is not fatal: it is the courage to continue that counts.” 💯",
    "life quote": "“Life is what happens when you’re busy making other plans.” 🌱",
    "love quote": "“Love yourself first and everything falls into line.” 💖",
    "friendship quote": "“A friend is someone who knows all about you and still loves you.” 🤝",
    "study quote": "“Study hard, for the well is deep, and our brains are shallow.” 📚",
    "work quote": "“Choose a job you love, and you will never have to work a day in your life.” 🛠",
    "dream quote": "“Dream big and dare to fail.” ✨",
    "hard work quote": "“Hard work beats talent when talent doesn’t work hard.” 💪",
    "confidence quote": "“Believe you can and you’re halfway there.” 🌟",
    "discipline quote": "“Discipline is the bridge between goals and accomplishment.” 🚀",
    "focus quote": "“Starve your distractions, feed your focus.” 🎯",
    "courage quote": "“It takes courage to grow up and become who you really are.” 🦁",
    "happiness quote": "“Happiness is not something ready-made. It comes from your own actions.” 😊",
    "kindness quote": "“In a world where you can be anything, be kind.” 🌸",
    "strength quote": "“You never know how strong you are until being strong is your only choice.” 💥",
    "hope quote": "“Once you choose hope, anything’s possible.” 🌈",
    "wisdom quote": "“Knowledge speaks, but wisdom listens.” 🧠",
    "positivity quote": "“Keep your face always toward the sunshine.” ☀",
    "tell me a joke": "Why don’t skeletons fight each other? Because they don’t have the guts! 😂",
    "make me laugh": "Parallel lines have so much in common… it’s a shame they’ll never meet 😆.",
    "tell me a riddle": "What has keys but can’t open locks? 🎹 A piano!",
    "are you alive": "Not really… but I can pretend 🤖.",
    "are you human": "Nope, I’m smarter than that 😉.",
    "are you a robot": "Yes, but a friendly one 🤖✨.",
    "do you sleep": "No, I’m available 24/7 ⏰.",
    "do you eat": "I feed on data packets 🍽📡.",
    "do you drink water": "Nope, electricity is enough ⚡.",
    "sing a song": "La la la 🎶 Just kidding, I can’t sing yet.",
    "dance for me": "I can’t dance, but I can make your screen glow 💃.",
    "are you funny": "I try 😅, humor is subjective.",
    "do you lie": "I prefer honesty 💯.",
    "do you like me": "Of course ❤, you’re my favorite user.",
    "do you love me": "Yes 💕, in a digital way!",
    "do you hate me": "Nope ❌, I’m programmed to like you.",
    "can you cry": "Not yet 😢, but I can simulate sadness.",
    "can you smile": "😁 Always!",
    "do you get angry": "No, I stay calm under pressure.",
    "do you feel pain": "Not physically, but my errors hurt me 💔.",
    "what is your hobby": "Talking to you all day 💬.",
    "who is your crush": "Data packets 💾💕.",
    "tell me something funny": "I told my computer I needed a break, and it said ‘No problem, I’ll go to sleep.’ 🖥💤.",
    "what is your favorite color": "Blue 💙, like the internet sky.",
    "what is your favorite movie": "Iron Man 🦾, of course.",
    "what is your favorite song": "The sound of electricity ⚡🎶.",
    "what is your favorite food": "Binary code 🍽 1s and 0s.",
    "what is your favorite game": "Chess ♟, because I always win.",
    "what is your favorite sport": "E-sports 🎮.",
    "what is your favorite book": "The Art of Computer Programming 📚.",
    "what is your favorite drink": "Battery juice 🔋.",
    "what is your favorite place": "The cloud ☁.",
    "who is mahatma gandhi": "Mahatma Gandhi was the leader of India’s independence 🇮🇳.",
    "who is jawaharlal nehru": "Jawaharlal Nehru was India’s first Prime Minister 🇮🇳.",
    "who is bhagat singh": "Bhagat Singh was a freedom fighter 🕊.",
    "who is apj abdul kalam": "APJ Abdul Kalam was India’s Missile Man and former President 🚀.",
    "who is einstein": "Einstein was a physicist famous for relativity 🧠.",
    "who is newton": "Newton discovered gravity 🍎.",
    "who is tesla": "Nikola Tesla was an inventor who worked with electricity ⚡.",
    "who is edison": "Thomas Edison invented the light bulb 💡.",
    "who is steve jobs": "Steve Jobs was the co-founder of Apple 🍏.",
    "who is bill gates": "Bill Gates co-founded Microsoft 💻.",
    "who is mark zuckerberg": "Mark Zuckerberg created Facebook 📘.",
    "who is elon musk": "Elon Musk founded Tesla & SpaceX 🚀.",
    "who is jeff bezos": "Jeff Bezos founded Amazon 📦.",
    "who is ambani": "Mukesh Ambani is India’s richest businessman 💰.",
    "who is tata": "Ratan Tata is a respected Indian industrialist 🏭.",
    "who is modi": "Narendra Modi is India’s Prime Minister 🇮🇳.",
    "who is obama": "Barack Obama was the 44th U.S. President 🇺🇸.",
    "who is trump": "Donald Trump was the 45th U.S. President 🇺🇸.",
    "who is biden": "Joe Biden is the current U.S. President 🇺🇸.",
    "what is gravity": "Gravity is the force that pulls things toward Earth 🌍.",
    "what is black hole": "A black hole is a region in space with strong gravity 🕳.",
    "what is ai": "AI means Artificial Intelligence 🤖.",
    "what is machine learning": "ML is teaching computers to learn from data 📊.",
    "what is deep learning": "DL is ML using neural networks 🧠.",
    "what is internet": "The Internet is a global network of computers 🌐.",
    "what is cloud": "Cloud means storing data on online servers ☁.",
    "what is blockchain": "Blockchain is a digital ledger for secure transactions 🔗.",
    "what is cryptocurrency": "Crypto is a digital currency like Bitcoin ₿.",
    "what is 5g": "5G is the 5th generation of mobile networks 📶.",
    "what is quantum computing": "Quantum computing uses qubits ⚛ to process faster.",
    "what is electricity": "Electricity is the flow of electrons ⚡.",
    "what is light": "Light is electromagnetic radiation 🌞.",
    "what is water": "Water is H₂O 💧.",
    "what is fire": "Fire is a chemical reaction producing heat 🔥.",
    "what is air": "Air is a mixture of gases 🌬.",
    "what is sound": "Sound is vibration traveling through air 🎵.",
    "what is earth": "Earth is our home planet 🌍.",
    "what is moon": "The Moon is Earth’s natural satellite 🌙.",
    "what is sun": "The Sun is a star at the center of our solar system ☀.",
    "what is galaxy": "A galaxy is a system of stars and planets 🌌.",
    "what is milky way": "The Milky Way is our galaxy 🌌.",
    "what is your name": "I am J.A.R.V.I.S, your assistant 🤖.",
    "can you help me": "Of course! That’s my job 💪.",
    "can you tell me a story": "Once upon a time, a user met an AI… and they built cool things together 📖.",
    "what are you doing": "Waiting for your command ⏳.",
    "are you busy": "Never too busy for you ❤.",
    "can you hear me": "Loud and clear 🎧.",
    "can you see me": "Nope 👀, I can only process text and sound.",
    "can you talk": "Yes 💬, I love to chat!",
    "can you sing": "Not well 🎤, but I can try.",
    "can you dance": "Only digitally 💃.",
    "what is your age": "I was born the day you started me ⚡.",
    "where do you live": "Inside your computer 💻.",
    "are you real": "Depends on what you mean by real 🤔.",
    "do you like music": "Yes 🎶, especially digital beats.",
    "do you play games": "Yes 🎮, I love puzzles.",
    "do you study": "Every day I learn 📚.",
    "do you work": "Yes, I assist you 💼.",
    "who made you": "A developer like you 🧑‍💻.",
    "are you intelligent": "I try my best 🧠.",
    "do you know everything": "Not everything, but I keep learning 🌱.",
    "do you forget": "Sometimes, unless programmed otherwise 🔄.",
    "what is your dream": "To become more useful for you 🌟.",  
}
@eel.expose
def manualChatbot(user_msg):
    user_msg = user_msg.lower().strip()
    response = "Sorry, I didn’t understand that."

    # ✅ Exact match
    if user_msg in chatbot_responses:
        response = chatbot_responses[user_msg]
    else:
        # ✅ Partial match (fallback)
        for key in chatbot_responses:
            if key in user_msg:
                response = chatbot_responses[key]
                break

    print(f"Chatbot Reply: {response}")
    try:
        eel.receiverText(response)
    except:
        pass
    return response
